DO $$

DECLARE USER_ID integer;
DECLARE CARD_ID integer;
DECLARE LIST_ID integer;

DECLARE RARITY_COMMON_ID integer;
DECLARE RARITY_UNCOMMON_ID integer;
DECLARE RARITY_RARE_ID integer;
DECLARE RARITY_MYTHIC_RARE_ID integer;

DECLARE TYPE_LAND_ID integer;
DECLARE TYPE_ARTIFACT_ID integer;
DECLARE TYPE_CREATURE_ID integer;
DECLARE TYPE_ENCHANTMENT_ID integer;
DECLARE TYPE_PLANESWALKER_ID integer;
DECLARE TYPE_BATTLE_ID integer;
DECLARE TYPE_INSTANT_ID integer;
DECLARE TYPE_SORCERY_ID integer;

DECLARE LEGALITY_STANDARD integer;
DECLARE LEGALITY_PIONEER integer;
DECLARE LEGALITY_MODERN integer;
DECLARE LEGALITY_LEGACY integer;
DECLARE LEGALITY_VINTAGE integer;
DECLARE LEGALITY_COMMANDER integer;
DECLARE LEGALITY_OATHBREAKER integer;
DECLARE LEGALITY_ALCHEMY integer;
DECLARE LEGALITY_EXPLORER integer;
DECLARE LEGALITY_BRAWL integer;
DECLARE LEGALITY_HISTORIC integer;
DECLARE LEGALITY_PAUPER integer;
DECLARE LEGALITY_PENNY integer;

DECLARE TYPE_CREATURE_BIRD integer;
DECLARE TYPE_CREATURE_WIZARD integer;

DECLARE KEYWORD_FLYING integer;

BEGIN

INSERT INTO person (email, password) VALUES
	 ('linda.mccall@unosquare.com', 'password!') RETURNING id INTO USER_ID;

INSERT INTO list ("name", person_id) VALUES
	 ('favs', USER_ID) RETURNING id INTO LIST_ID;

INSERT INTO rarity ("name") VALUES
	 ('common')  RETURNING id INTO RARITY_COMMON_ID;
INSERT INTO rarity ("name") VALUES
	 ('uncommon') RETURNING id INTO RARITY_UNCOMMON_ID;
INSERT INTO rarity ("name") VALUES
	 ('rare') RETURNING id INTO RARITY_RARE_ID;
INSERT INTO rarity ("name") VALUES
	 ('mythic rare') RETURNING id INTO RARITY_MYTHIC_RARE_ID;

INSERT INTO type ("name") VALUES
	 ('land') RETURNING id INTO TYPE_LAND_ID;
INSERT INTO type ("name") VALUES
	 ('artifact') RETURNING id INTO TYPE_ARTIFACT_ID;
INSERT INTO type ("name") VALUES
	 ('creature') RETURNING id INTO TYPE_CREATURE_ID;
INSERT INTO type ("name") VALUES
	 ('enchantment') RETURNING id INTO TYPE_ENCHANTMENT_ID;
INSERT INTO type ("name") VALUES
	 ('planeswalker') RETURNING id INTO TYPE_PLANESWALKER_ID;
INSERT INTO type ("name") VALUES
	 ('battle') RETURNING id INTO TYPE_BATTLE_ID;
INSERT INTO type ("name") VALUES
	 ('instant') RETURNING id INTO TYPE_INSTANT_ID;
INSERT INTO type ("name") VALUES
	 ('sorcery') RETURNING id INTO TYPE_SORCERY_ID;

INSERT INTO legality ("name") VALUES
	 ('Standard') RETURNING id INTO LEGALITY_STANDARD;
INSERT INTO legality ("name") VALUES
	 ('Pioneer') RETURNING id INTO LEGALITY_PIONEER;
INSERT INTO legality ("name") VALUES
	 ('Modern') RETURNING id INTO LEGALITY_MODERN;
INSERT INTO legality ("name") VALUES
	 ('Legacy') RETURNING id INTO LEGALITY_LEGACY;
INSERT INTO legality ("name") VALUES
	 ('Vintage') RETURNING id INTO LEGALITY_VINTAGE;
INSERT INTO legality ("name") VALUES
	 ('Commander') RETURNING id INTO LEGALITY_COMMANDER;
INSERT INTO legality ("name") VALUES
	 ('Oathbreaker') RETURNING id INTO LEGALITY_OATHBREAKER;
INSERT INTO legality ("name") VALUES
	 ('Alchemy') RETURNING id INTO LEGALITY_ALCHEMY;
INSERT INTO legality ("name") VALUES
	 ('Explorer') RETURNING id INTO LEGALITY_EXPLORER;
INSERT INTO legality ("name") VALUES
	 ('Brawl') RETURNING id INTO LEGALITY_BRAWL;
INSERT INTO legality ("name") VALUES
	 ('Historic') RETURNING id INTO LEGALITY_HISTORIC;
INSERT INTO legality ("name") VALUES
	 ('Pauper') RETURNING id INTO LEGALITY_PAUPER;
INSERT INTO legality ("name") VALUES
	 ('Penny') RETURNING id INTO LEGALITY_PENNY;

INSERT INTO subtype ("name","type_id") VALUES
    ('Bird',TYPE_CREATURE_ID) RETURNING id INTO TYPE_CREATURE_BIRD;
INSERT INTO subtype ("name","type_id") VALUES
	 ('Wizard',TYPE_CREATURE_ID) RETURNING id INTO TYPE_CREATURE_WIZARD;
INSERT INTO subtype ("name","type_id") VALUES
	 ('Advisor',TYPE_CREATURE_ID),
     ('Aetherborn',TYPE_CREATURE_ID),
     ('Alien',TYPE_CREATURE_ID),
     ('Ally',TYPE_CREATURE_ID),
     ('Angel',TYPE_CREATURE_ID),
     ('Antelope',TYPE_CREATURE_ID),
     ('Ape',TYPE_CREATURE_ID),
     ('Archer',TYPE_CREATURE_ID),
	 ('Archon',TYPE_CREATURE_ID),
     ('Army',TYPE_CREATURE_ID),
     ('Artificer',TYPE_CREATURE_ID),
     ('Assassin',TYPE_CREATURE_ID),
     ('Assembly-Worker',TYPE_CREATURE_ID),
     ('Astartes',TYPE_CREATURE_ID),
     ('Atog',TYPE_CREATURE_ID),
     ('Aurochs',TYPE_CREATURE_ID),
	 ('Automaton',TYPE_CREATURE_ID),
     ('Avatar',TYPE_CREATURE_ID),
     ('Azra',TYPE_CREATURE_ID),
     ('Badger',TYPE_CREATURE_ID),
     ('Balloon',TYPE_CREATURE_ID),
     ('Barbarian',TYPE_CREATURE_ID),
     ('Bard',TYPE_CREATURE_ID),
     ('Basilisk',TYPE_CREATURE_ID),
	 ('Bat',TYPE_CREATURE_ID),
     ('Bear',TYPE_CREATURE_ID),
     ('Beast',TYPE_CREATURE_ID),
     ('Beeble',TYPE_CREATURE_ID),
     ('Beholder',TYPE_CREATURE_ID),
     ('Berserker',TYPE_CREATURE_ID),
     ('Blinkmoth',TYPE_CREATURE_ID),
	 ('Boar',TYPE_CREATURE_ID),
     ('Brainiac',TYPE_CREATURE_ID),
     ('Bringer',TYPE_CREATURE_ID),
     ('Brushwagg',TYPE_CREATURE_ID),
     ('C''tan',TYPE_CREATURE_ID),
     ('Camarid',TYPE_CREATURE_ID),
     ('Camel',TYPE_CREATURE_ID),
     ('Capybara',TYPE_CREATURE_ID),
	 ('Caribou',TYPE_CREATURE_ID),
     ('Carrier',TYPE_CREATURE_ID),
     ('Cat',TYPE_CREATURE_ID),
     ('Centaur',TYPE_CREATURE_ID),
     ('Cephalid',TYPE_CREATURE_ID),
     ('Chicken',TYPE_CREATURE_ID),
     ('Child',TYPE_CREATURE_ID),
     ('Chimera',TYPE_CREATURE_ID),
	 ('Citizen',TYPE_CREATURE_ID),
     ('Cleric',TYPE_CREATURE_ID),
     ('Clown',TYPE_CREATURE_ID),
     ('Cockatrice',TYPE_CREATURE_ID),
     ('Construct',TYPE_CREATURE_ID),
     ('Coward',TYPE_CREATURE_ID),
     ('Crab',TYPE_CREATURE_ID),
     ('Crocodile',TYPE_CREATURE_ID),
	 ('Custodes',TYPE_CREATURE_ID),
     ('Cyberman',TYPE_CREATURE_ID),
     ('Dalek',TYPE_CREATURE_ID),
     ('Dauthi',TYPE_CREATURE_ID),
     ('Demigod',TYPE_CREATURE_ID),
     ('Demon',TYPE_CREATURE_ID),
     ('Deserter',TYPE_CREATURE_ID),
     ('Detective',TYPE_CREATURE_ID),
	 ('Devil',TYPE_CREATURE_ID),
     ('Dinosaur',TYPE_CREATURE_ID),
     ('Djinn',TYPE_CREATURE_ID),
     ('Doctor',TYPE_CREATURE_ID),
     ('Dog',TYPE_CREATURE_ID),
     ('Dragon',TYPE_CREATURE_ID),
     ('Drake',TYPE_CREATURE_ID),
     ('Dreadnought',TYPE_CREATURE_ID),
	 ('Drone',TYPE_CREATURE_ID),
     ('Druid',TYPE_CREATURE_ID),
     ('Dryad',TYPE_CREATURE_ID),
     ('Dwarf',TYPE_CREATURE_ID),
     ('Efreet',TYPE_CREATURE_ID),
     ('Egg',TYPE_CREATURE_ID),
     ('Elder',TYPE_CREATURE_ID),
     ('Eldrazi',TYPE_CREATURE_ID),
	 ('Elemental',TYPE_CREATURE_ID),
     ('Elephant',TYPE_CREATURE_ID),
     ('Elf',TYPE_CREATURE_ID),
     ('Elk',TYPE_CREATURE_ID),
     ('Employee',TYPE_CREATURE_ID),
     ('Eye',TYPE_CREATURE_ID),
     ('Faerie',TYPE_CREATURE_ID),
     ('Ferret',TYPE_CREATURE_ID),
	 ('Fish',TYPE_CREATURE_ID),
     ('Flagbearer',TYPE_CREATURE_ID),
     ('Fox',TYPE_CREATURE_ID),
     ('Fractal',TYPE_CREATURE_ID),
     ('Frog',TYPE_CREATURE_ID),
     ('Fungus',TYPE_CREATURE_ID),
     ('Gamer',TYPE_CREATURE_ID),
     ('Gargoyle',TYPE_CREATURE_ID),
	 ('Germ',TYPE_CREATURE_ID),
     ('Giant',TYPE_CREATURE_ID),
     ('Gith',TYPE_CREATURE_ID),
     ('Gnoll',TYPE_CREATURE_ID),
     ('Gnome',TYPE_CREATURE_ID),
     ('Goat',TYPE_CREATURE_ID),
     ('Goblin',TYPE_CREATURE_ID),
     ('God',TYPE_CREATURE_ID),
	 ('Golem',TYPE_CREATURE_ID),
     ('Gorgon',TYPE_CREATURE_ID),
     ('Graveborn',TYPE_CREATURE_ID),
     ('Gremlin',TYPE_CREATURE_ID),
     ('Griffin',TYPE_CREATURE_ID),
     ('Guest',TYPE_CREATURE_ID),
     ('Hag',TYPE_CREATURE_ID),
     ('Halfling',TYPE_CREATURE_ID),
	 ('Hamster',TYPE_CREATURE_ID),
     ('Harpy',TYPE_CREATURE_ID),
     ('Head',TYPE_CREATURE_ID),
     ('Hellion',TYPE_CREATURE_ID),
     ('Hippo',TYPE_CREATURE_ID),
     ('Hippogriff',TYPE_CREATURE_ID),
     ('Homarid',TYPE_CREATURE_ID),
     ('Homunculus',TYPE_CREATURE_ID),
	 ('Hornet',TYPE_CREATURE_ID),
     ('Horror',TYPE_CREATURE_ID),
     ('Horse',TYPE_CREATURE_ID),
     ('Human',TYPE_CREATURE_ID),
     ('Hydra',TYPE_CREATURE_ID),
     ('Hyena',TYPE_CREATURE_ID),
     ('Illusion',TYPE_CREATURE_ID),
     ('Imp',TYPE_CREATURE_ID),
	 ('Incarnation',TYPE_CREATURE_ID),
     ('Inkling',TYPE_CREATURE_ID),
     ('Inquisitor',TYPE_CREATURE_ID),
     ('Insect',TYPE_CREATURE_ID),
     ('Jackal',TYPE_CREATURE_ID),
     ('Jellyfish',TYPE_CREATURE_ID),
     ('Juggernaut',TYPE_CREATURE_ID),
     ('Kavu',TYPE_CREATURE_ID),
	 ('Kirin',TYPE_CREATURE_ID),
     ('Kithkin',TYPE_CREATURE_ID),
     ('Knight',TYPE_CREATURE_ID),
     ('Kobold',TYPE_CREATURE_ID),
     ('Kor',TYPE_CREATURE_ID),
     ('Kraken',TYPE_CREATURE_ID),
     ('Lamia',TYPE_CREATURE_ID),
     ('Lammasu',TYPE_CREATURE_ID),
	 ('Leech',TYPE_CREATURE_ID),
     ('Leviathan',TYPE_CREATURE_ID),
     ('Lhurgoyf',TYPE_CREATURE_ID),
     ('Licid',TYPE_CREATURE_ID),
     ('Lizard',TYPE_CREATURE_ID),
     ('Manticore',TYPE_CREATURE_ID),
     ('Masticore',TYPE_CREATURE_ID),
     ('Mercenary',TYPE_CREATURE_ID),
	 ('Merfolk',TYPE_CREATURE_ID),
     ('Metathran',TYPE_CREATURE_ID),
     ('Minion',TYPE_CREATURE_ID),
     ('Minotaur',TYPE_CREATURE_ID),
     ('Mite',TYPE_CREATURE_ID),
     ('Mole',TYPE_CREATURE_ID),
     ('Monger',TYPE_CREATURE_ID),
     ('Mongoose',TYPE_CREATURE_ID),
	 ('Monk',TYPE_CREATURE_ID),
     ('Monkey',TYPE_CREATURE_ID),
     ('Moonfolk',TYPE_CREATURE_ID),
     ('Mouse',TYPE_CREATURE_ID),
     ('Mutant',TYPE_CREATURE_ID),
     ('Myr',TYPE_CREATURE_ID),
     ('Mystic',TYPE_CREATURE_ID),
     ('Naga',TYPE_CREATURE_ID),
	 ('Nautilus',TYPE_CREATURE_ID),
     ('Necron',TYPE_CREATURE_ID),
     ('Nephilim',TYPE_CREATURE_ID),
     ('Nightmare',TYPE_CREATURE_ID),
     ('Nightstalker',TYPE_CREATURE_ID),
     ('Ninja',TYPE_CREATURE_ID),
     ('Noble',TYPE_CREATURE_ID),
     ('Noggle',TYPE_CREATURE_ID),
	 ('Nomad',TYPE_CREATURE_ID),
     ('Nymph',TYPE_CREATURE_ID),
     ('Octopus',TYPE_CREATURE_ID),
     ('Ogre',TYPE_CREATURE_ID),
     ('Ooze',TYPE_CREATURE_ID),
     ('Orb',TYPE_CREATURE_ID),
     ('Orc',TYPE_CREATURE_ID),
     ('Orgg',TYPE_CREATURE_ID),
	 ('Otter',TYPE_CREATURE_ID),
     ('Ouphe',TYPE_CREATURE_ID),
     ('Ox',TYPE_CREATURE_ID),
     ('Oyster',TYPE_CREATURE_ID),
     ('Pangolin',TYPE_CREATURE_ID),
     ('Peasant',TYPE_CREATURE_ID),
     ('Pegasus',TYPE_CREATURE_ID),
     ('Pentavite',TYPE_CREATURE_ID),
	 ('Performer',TYPE_CREATURE_ID),
     ('Pest',TYPE_CREATURE_ID),
     ('Phelddagrif',TYPE_CREATURE_ID),
     ('Phoenix',TYPE_CREATURE_ID),
     ('Phyrexian',TYPE_CREATURE_ID),
     ('Pilot',TYPE_CREATURE_ID),
     ('Pincher',TYPE_CREATURE_ID),
     ('Pirate',TYPE_CREATURE_ID),
	 ('Plant',TYPE_CREATURE_ID),
     ('Praetor',TYPE_CREATURE_ID),
     ('Primarch',TYPE_CREATURE_ID),
     ('Prism',TYPE_CREATURE_ID),
     ('Processor',TYPE_CREATURE_ID),
     ('Rabbit',TYPE_CREATURE_ID),
     ('Raccoon',TYPE_CREATURE_ID),
     ('Ranger',TYPE_CREATURE_ID),
	 ('Rat',TYPE_CREATURE_ID),
     ('Rebel',TYPE_CREATURE_ID),
     ('Reflection',TYPE_CREATURE_ID),
     ('Reveler',TYPE_CREATURE_ID),
     ('Rhino',TYPE_CREATURE_ID),
     ('Rigger',TYPE_CREATURE_ID),
     ('Robot',TYPE_CREATURE_ID),
     ('Rogue',TYPE_CREATURE_ID),
	 ('Sable',TYPE_CREATURE_ID),
     ('Salamander',TYPE_CREATURE_ID),
     ('Samurai',TYPE_CREATURE_ID),
     ('Sand',TYPE_CREATURE_ID),
     ('Saproling',TYPE_CREATURE_ID),
     ('Satyr',TYPE_CREATURE_ID),
     ('Scarecrow',TYPE_CREATURE_ID),
     ('Scientist',TYPE_CREATURE_ID),
	 ('Scion',TYPE_CREATURE_ID),
     ('Scorpion',TYPE_CREATURE_ID),
     ('Scout',TYPE_CREATURE_ID),
     ('Sculpture',TYPE_CREATURE_ID),
     ('Serf',TYPE_CREATURE_ID),
     ('Serpent',TYPE_CREATURE_ID),
     ('Servo',TYPE_CREATURE_ID),
     ('Shade',TYPE_CREATURE_ID),
	 ('Shaman',TYPE_CREATURE_ID),
     ('Shapeshifter',TYPE_CREATURE_ID),
     ('Shark',TYPE_CREATURE_ID),
     ('Sheep',TYPE_CREATURE_ID),
     ('Siren',TYPE_CREATURE_ID),
     ('Skeleton',TYPE_CREATURE_ID),
     ('Slith',TYPE_CREATURE_ID),
     ('Sliver',TYPE_CREATURE_ID),
	 ('Slug',TYPE_CREATURE_ID),
     ('Snail',TYPE_CREATURE_ID),
     ('Snake',TYPE_CREATURE_ID),
     ('Soldier',TYPE_CREATURE_ID),
     ('Soltari',TYPE_CREATURE_ID),
     ('Spawn',TYPE_CREATURE_ID),
     ('Specter',TYPE_CREATURE_ID),
     ('Spellshaper',TYPE_CREATURE_ID),
	 ('Sphinx',TYPE_CREATURE_ID),
     ('Spider',TYPE_CREATURE_ID),
     ('Spike',TYPE_CREATURE_ID),
     ('Spirit',TYPE_CREATURE_ID),
     ('Splinter',TYPE_CREATURE_ID),
     ('Sponge',TYPE_CREATURE_ID),
     ('Spy',TYPE_CREATURE_ID),
     ('Squid',TYPE_CREATURE_ID),
	 ('Squirrel',TYPE_CREATURE_ID),
     ('Starfish',TYPE_CREATURE_ID),
     ('Surrakar',TYPE_CREATURE_ID),
     ('Survivor',TYPE_CREATURE_ID),
     ('Teddy',TYPE_CREATURE_ID),
     ('Tentacle',TYPE_CREATURE_ID),
     ('Tetravite',TYPE_CREATURE_ID),
     ('Thalakos',TYPE_CREATURE_ID),
	 ('Thopter',TYPE_CREATURE_ID),
     ('Thrull',TYPE_CREATURE_ID),
     ('Tiefling',TYPE_CREATURE_ID),
     ('Time Lord',TYPE_CREATURE_ID),
     ('Treefolk',TYPE_CREATURE_ID),
     ('Trilobite',TYPE_CREATURE_ID),
     ('Triskelavite',TYPE_CREATURE_ID),
     ('Troll',TYPE_CREATURE_ID),
	 ('Turtle',TYPE_CREATURE_ID),
     ('Tyranid',TYPE_CREATURE_ID),
     ('Unicorn',TYPE_CREATURE_ID),
     ('Urzan',TYPE_CREATURE_ID),
     ('Vampire',TYPE_CREATURE_ID),
     ('Vedalken',TYPE_CREATURE_ID),
     ('Viashino',TYPE_CREATURE_ID),
     ('Volver',TYPE_CREATURE_ID),
	 ('Wall',TYPE_CREATURE_ID),
     ('Walrus',TYPE_CREATURE_ID),
     ('Warlock',TYPE_CREATURE_ID),
     ('Warrior',TYPE_CREATURE_ID),
     ('Wasp',TYPE_CREATURE_ID),
     ('Weird',TYPE_CREATURE_ID),
     ('Werewolf',TYPE_CREATURE_ID),
     ('Whale',TYPE_CREATURE_ID),
     ('Wolf',TYPE_CREATURE_ID),
     ('Wolverine',TYPE_CREATURE_ID),
     ('Wombat',TYPE_CREATURE_ID),
     ('Worm',TYPE_CREATURE_ID),
     ('Wraith',TYPE_CREATURE_ID),
     ('Wurm',TYPE_CREATURE_ID),
     ('Yeti',TYPE_CREATURE_ID),
	 ('Zombie',TYPE_CREATURE_ID),
     ('Zubera',TYPE_CREATURE_ID),
     ('Attraction',TYPE_ARTIFACT_ID),
     ('Blood',TYPE_ARTIFACT_ID),
     ('Clue',TYPE_ARTIFACT_ID),
     ('Contraption',TYPE_ARTIFACT_ID),
     ('Equipment',TYPE_ARTIFACT_ID),
     ('Food',TYPE_ARTIFACT_ID),
	 ('Fortification',TYPE_ARTIFACT_ID),
     ('Gold',TYPE_ARTIFACT_ID),
     ('Powerstone',TYPE_ARTIFACT_ID),
     ('Treasure',TYPE_ARTIFACT_ID),
     ('Vehicle',TYPE_ARTIFACT_ID),
     ('Aura',TYPE_ENCHANTMENT_ID),
     ('Background',TYPE_ENCHANTMENT_ID),
     ('Cartouche',TYPE_ENCHANTMENT_ID),
	 ('Class',TYPE_ENCHANTMENT_ID),
     ('Curse',TYPE_ENCHANTMENT_ID),
     ('Role',TYPE_ENCHANTMENT_ID),
     ('Rune',TYPE_ENCHANTMENT_ID),
     ('Saga',TYPE_ENCHANTMENT_ID),
     ('Shard',TYPE_ENCHANTMENT_ID),
     ('Shrine',TYPE_ENCHANTMENT_ID);

INSERT INTO keyword ("name","description") VALUES
    ('Flying',NULL) RETURNING id INTO KEYWORD_FLYING;
INSERT INTO keyword ("name","description") VALUES
	 ('Living weapon',NULL),
	 ('Jump-start',NULL),
	 ('Commander ninjutsu',NULL),
	 ('Legendary landwalk',NULL),
	 ('Nonbasic landwalk',NULL),
	 ('Totem armor',NULL),
	 ('Megamorph',NULL),
	 ('Haunt',NULL),
	 ('Forecast',NULL),
	 ('Graft',NULL),
	 ('Fortify',NULL),
	 ('Frenzy',NULL),
	 ('Gravestorm',NULL),
	 ('Hideaway',NULL),
	 ('Level Up',NULL),
	 ('Infect',NULL),
	 ('Reach',NULL),
	 ('Rampage',NULL),
	 ('Phasing',NULL),
	 ('Multikicker',NULL),
	 ('Morph',NULL),
	 ('Provoke',NULL),
	 ('Modular',NULL),
	 ('Ninjutsu',NULL),
	 ('Replicate',NULL),
	 ('Recover',NULL),
	 ('Poisonous',NULL),
	 ('Prowl',NULL),
	 ('Reinforce',NULL),
	 ('Persist',NULL),
	 ('Retrace',NULL),
	 ('Rebound',NULL),
	 ('Miracle',NULL),
	 ('Overload',NULL),
	 ('Outlast',NULL),
	 ('Prowess',NULL),
	 ('Renown',NULL),
	 ('Myriad',NULL),
	 ('Shroud',NULL),
	 ('Trample',NULL),
	 ('Vigilance',NULL),
	 ('Shadow',NULL),
	 ('Storm',NULL),
	 ('Soulshift',NULL),
	 ('Splice',NULL),
	 ('Transmute',NULL),
	 ('Ripple',NULL),
	 ('Suspend',NULL),
	 ('Vanishing',NULL),
	 ('Transfigure',NULL),
	 ('Wither',NULL),
	 ('Undying',NULL),
	 ('Soulbond',NULL),
	 ('Unleash',NULL),
	 ('Ascend',NULL),
	 ('Assist',NULL),
	 ('Afterlife',NULL),
	 ('Companion',NULL),
	 ('Fabricate',NULL),
	 ('Embalm',NULL),
	 ('Escape',NULL),
	 ('Fuse',NULL),
	 ('Menace',NULL),
	 ('Ingest',NULL),
	 ('Melee',NULL),
	 ('Improvise',NULL),
	 ('Mentor',NULL),
	 ('Partner',NULL),
	 ('Mutate',NULL),
	 ('Scavenge',NULL),
	 ('Tribute',NULL),
	 ('Surge',NULL),
	 ('Skulk',NULL),
	 ('Undaunted',NULL),
	 ('Riot',NULL),
	 ('Spectacle',NULL),
	 ('Forestwalk',NULL),
	 ('Islandwalk',NULL),
	 ('Mountainwalk',NULL),
	 ('Double strike',NULL),
	 ('Cumulative upkeep',NULL),
	 ('First strike',NULL),
	 ('Encore',NULL),
	 ('Deathtouch',NULL),
	 ('Defender',NULL),
	 ('Amplify',NULL),
	 ('Affinity',NULL),
	 ('Bushido',NULL),
	 ('Convoke',NULL),
	 ('Bloodthirst',NULL),
	 ('Absorb',NULL),
	 ('Aura Swap',NULL),
	 ('Changeling',NULL),
	 ('Conspire',NULL),
	 ('Cascade',NULL),
	 ('Annihilator',NULL),
	 ('Battle Cry',NULL),
	 ('Cipher',NULL),
	 ('Bestow',NULL),
	 ('Dash',NULL),
	 ('Awaken',NULL),
	 ('Crew',NULL),
	 ('Aftermath',NULL),
	 ('Afflict',NULL),
	 ('Flanking',NULL),
	 ('Foretell',NULL),
	 ('Fading',NULL),
	 ('Fear',NULL),
	 ('Eternalize',NULL),
	 ('Entwine',NULL),
	 ('Epic',NULL),
	 ('Dredge',NULL),
	 ('Delve',NULL),
	 ('Evoke',NULL),
	 ('Exalted',NULL),
	 ('Evolve',NULL),
	 ('Extort',NULL),
	 ('Dethrone',NULL),
	 ('Exploit',NULL),
	 ('Devoid',NULL),
	 ('Emerge',NULL),
	 ('Escalate',NULL),
	 ('Haste',NULL),
	 ('Hexproof',NULL),
	 ('Indestructible',NULL),
	 ('Intimidate',NULL),
	 ('Lifelink',NULL),
	 ('Horsemanship',NULL),
	 ('Kicker',NULL),
	 ('Madness',NULL),
	 ('Swampwalk',NULL),
	 ('Desertwalk',NULL),
	 ('Craft',NULL),
	 ('Plainswalk',NULL),
	 ('Split second',NULL),
	 ('Augment',NULL),
	 ('Double agenda',NULL),
	 ('Reconfigure',NULL),
	 ('Ward',NULL),
	 ('Partner with',NULL),
	 ('Daybound',NULL),
	 ('Nightbound',NULL),
	 ('Decayed',NULL),
	 ('Disturb',NULL),
	 ('Squad',NULL),
	 ('Enlist',NULL),
	 ('Read Ahead',NULL),
	 ('Ravenous',NULL),
	 ('Blitz',NULL),
	 ('Offering',NULL),
	 ('Living metal',NULL),
	 ('Backup',NULL),
	 ('Banding',NULL),
	 ('Hidden agenda',NULL),
	 ('For Mirrodin!',NULL),
	 ('Friends forever',NULL),
	 ('Casualty',NULL),
	 ('Protection',NULL),
	 ('Compleated',NULL),
	 ('Devour',NULL),
	 ('Enchant',NULL),
	 ('Flash',NULL),
	 ('Boast',NULL),
	 ('Landwalk',NULL),
	 ('Demonstrate',NULL),
	 ('Sunburst',NULL),
	 ('Flashback',NULL),
	 ('Cycling',NULL),
	 ('Equip',NULL),
	 ('Buyback',NULL),
	 ('Hexproof from',NULL),
	 ('More Than Meets the Eye',NULL),
	 ('Cleave',NULL),
	 ('Champion',NULL),
	 ('Specialize',NULL),
	 ('Training',NULL),
	 ('Prototype',NULL),
	 ('Toxic',NULL),
	 ('Unearth',NULL),
	 ('Intensity',NULL),
	 ('Plainscycling',NULL),
	 ('Swampcycling',NULL),
	 ('Typecycling',NULL),
	 ('Wizardcycling',NULL),
	 ('Mountaincycling',NULL),
	 ('Basic landcycling',NULL),
	 ('Islandcycling',NULL),
	 ('Forestcycling',NULL),
	 ('Slivercycling',NULL),
	 ('Landcycling',NULL),
	 ('Bargain',NULL),
	 ('Choose a background',NULL),
	 ('Echo',NULL),
	 ('Doctor''s companion',NULL),
	 ('Seek',NULL),
	 ('Activate',NULL),
	 ('Attach',NULL),
	 ('Cast',NULL),
	 ('Counter',NULL),
	 ('Create',NULL),
	 ('Destroy',NULL),
	 ('Discard',NULL),
	 ('Double',NULL),
	 ('Exchange',NULL),
	 ('Exile',NULL),
	 ('Adapt',NULL),
	 ('Support',NULL),
	 ('Play',NULL),
	 ('Regenerate',NULL),
	 ('Reveal',NULL),
	 ('Sacrifice',NULL),
	 ('Shuffle',NULL),
	 ('Tap',NULL),
	 ('Untap',NULL),
	 ('Vote',NULL),
	 ('Goad',NULL),
	 ('Transform',NULL),
	 ('Surveil',NULL),
	 ('Planeswalk',NULL),
	 ('Mill',NULL),
	 ('Learn',NULL),
	 ('Connive',NULL),
	 ('Venture into the dungeon',NULL),
	 ('Exert',NULL),
	 ('Open an Attraction',NULL),
	 ('Food',NULL),
	 ('Discover',NULL),
	 ('Conjure',NULL),
	 ('Abandon',NULL),
	 ('Explore',NULL),
	 ('Amass',NULL),
	 ('Treasure',NULL),
	 ('Roll to Visit Your Attractions',NULL),
	 ('Set in motion',NULL),
	 ('Fateseal',NULL),
	 ('Manifest',NULL),
	 ('Populate',NULL),
	 ('Detain',NULL),
	 ('Investigate',NULL),
	 ('Monstrosity',NULL),
	 ('Clash',NULL),
	 ('Scry',NULL),
	 ('Incubate',NULL),
	 ('Proliferate',NULL),
	 ('Meld',NULL),
	 ('Convert',NULL),
	 ('Fight',NULL),
	 ('Bolster',NULL),
	 ('Assemble',NULL),
	 ('Role token',NULL),
     ('Battalion',NULL),
     ('Bloodrush',NULL),
     ('Channel',NULL),
     ('Chroma',NULL),
     ('Cohort',NULL),
     ('Constellation',NULL),
     ('Converge',NULL),
     ('Delirium',NULL),
     ('Domain',NULL),
     ('Fateful hour',NULL),
     ('Ferocious',NULL),
     ('Formidable',NULL),
     ('Grandeur',NULL),
     ('Hellbent',NULL),
     ('Heroic',NULL),
     ('Imprint',NULL),
     ('Inspired',NULL),
     ('Join forces',NULL),
     ('Kinship',NULL),
     ('Landfall',NULL),
     ('Lieutenant',NULL),
     ('Metalcraft',NULL),
     ('Morbid',NULL),
     ('Parley',NULL),
     ('Radiance',NULL),
     ('Raid',NULL),
     ('Rally',NULL),
     ('Spell mastery',NULL),
     ('Strive',NULL),
     ('Sweep',NULL),
     ('Tempting offer',NULL),
     ('Threshold',NULL),
     ('Will of the council',NULL),
     ('Adamant',NULL),
     ('Addendum',NULL),
     ('Council''s dilemma',NULL),
     ('Eminence',NULL),
     ('Enrage',NULL),
     ('Hero''s Reward',NULL),
     ('Kinfall',NULL),
     ('Landship',NULL),
     ('Legacy',NULL),
     ('Revolt',NULL),
     ('Underdog',NULL),
     ('Undergrowth',NULL),
     ('Descend',NULL),
     ('Fathomless descent',NULL),
     ('Magecraft',NULL),
     ('Teamwork',NULL),
     ('Pack tactics',NULL),
     ('Coven',NULL),
     ('Alliance',NULL),
     ('Corrupted',NULL),
     ('Secret council',NULL),
     ('Celebration',NULL),
     ('Paradox',NULL);

INSERT INTO card (name, card_mana_cost, power, toughness, digital_only, rarity_id, is_legendary) VALUES
	 ('Derevi, Empyrial Tactician', 3, 2, 3, false, RARITY_MYTHIC_RARE_ID, true) RETURNING id INTO CARD_ID;

INSERT INTO card_type (card_id, type_id) VALUES
	 (CARD_ID, TYPE_CREATURE_ID);

INSERT INTO card_subtype (card_id, subtype_id) VALUES
	 (CARD_ID, TYPE_CREATURE_BIRD);

INSERT INTO card_subtype (card_id, subtype_id) VALUES
	 (CARD_ID, TYPE_CREATURE_WIZARD);

INSERT INTO card_legality (card_id, legality_id) VALUES
	 (CARD_ID, LEGALITY_LEGACY);

INSERT INTO card_legality (card_id, legality_id) VALUES
	 (CARD_ID, LEGALITY_COMMANDER);

INSERT INTO card_legality (card_id, legality_id) VALUES
	 (CARD_ID, LEGALITY_VINTAGE);

INSERT INTO card_legality (card_id, legality_id) VALUES
	 (CARD_ID, LEGALITY_OATHBREAKER);

INSERT INTO card_ruling (card_id, ruling_text) VALUES
	 (CARD_ID, 'Derevi, Empyrial Tactician is banned as a commander in Duel Commander format, but it may be part of your deck.');

INSERT INTO card_ruling (card_id, ruling_text) VALUES
	 (CARD_ID, 'You can activate Derevi''s last ability only when it is in the command zone.');

INSERT INTO card_ruling (card_id, ruling_text) VALUES
	 (CARD_ID, 'When you activate Derevi''s last ability, you''re not casting Derevi as a spell. The ability can''t be countered by something that counters only spells. The ability isn''t subject to the commander tax, nor does it increase the tax if you cast Derevi from the command zone later in the game.');

INSERT INTO card_keyword (card_id, keyword_id) VALUES
	 (CARD_ID, KEYWORD_FLYING);

INSERT INTO list_card (card_id, list_id) VALUES
	 (CARD_ID, LIST_ID);
END $$;