name: Deploy API

on:
  push:
    branches:
      - main
    paths:
      - 'card-search/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./card-search

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
      - name: Install AWS Lightsail Client
        run: |
          curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "lightsailctl"
          sudo mv "lightsailctl" "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl
      - name: Build and push image to Lightsail
        id: build-image
        run: |
          docker build --build-arg SPRING_DATASOURCE_URL="${{ secrets.DEV_DB_URL }}" --build-arg SPRING_DATASOURCE_USERNAME="${{ secrets.DEV_DB_USER }}" --build-arg SPRING_DATASOURCE_PASSWORD="${{ secrets.DEV_DB_PASSWORD }}" -t card-search:latest .
          aws lightsail push-container-image --region us-east-1 --service-name mtg-search-container --label card-search --image card-search:latest
      - name: Deploy Service
        run: |
          aws lightsail get-container-images --service-name mtg-search-container | jq --raw-output ".containerImages[0].image" > image.txt
          jq --arg image $(cat image.txt) '.containers.app.image = $image' container.template.json > container.json
          aws lightsail create-container-service-deployment --service-name mtg-search-container --cli-input-json file://$(pwd)/container.json
